---
- hosts: localhost
  become: True
  tasks:
  - name: Download kubeadm
    get_url:
      url: 'https://github.com/flanksource/konfigadm/releases/download/v0.5.3/konfigadm'
      dest: /usr/bin/
      mode: 'u+x'
  - name: create directory
    file:
      path: ~/projectdirec
      state: directory
      mode: '0777'
  - git:
      repo: 'https://github.com/akhilraj939/Learnings'
      dest: ~/projectdirec
  - name: Copy file
    copy:
      src: ~/projectdirec/konfigadm.yml
      dest: /tmp/
      mode: '0777'
  - name: execute
    shell: sudo konfigadm apply --config=/tmp/konfigadm.yml
  - name: Copy file 1
    copy:
      src: ~/projectdirec/kubeadm.yml
      dest: /tmp/
      mode: '0777'
  - name: execute1
    shell: sudo kubeadm init --config /tmp/kubeadm.yaml
  - name: Create a directory if it does not exist
    file:
      path: ~/.kube
      state: directory
      mode: '0777'
  - name: Copy file
    copy:
      src: /etc/kubernetes/admin.conf
      dest: ~/.kube/config
      mode: '0777'
  - name: execute
    shell: sudo kubectl --kubeconfig /etc/kubernetes/admin.conf apply -f https://docs.projectcalico.org/v3.8/manifests/calico.yaml
